// app/components/client-counter.tsx
import { h } from 'preact';
import { useState } from 'preact/hooks';

export default function ClientCounter({ count: initialCount = 0 }: { count?: number }) {
  const [count, setCount] = useState(initialCount);

  return (
    <div class="card bg-base-100 w-96 shadow-sm">
      <div class="card-body">
        <h2 class="card-title">Counter: {count}</h2>
        <p>A simple Preact/React client component with an interactive counter.</p>
        <div class="card-actions">
          <button className="btn btn-outline" onClick={() => setCount(count - 1)}>
            Decrement
          </button>
          <button className="btn btn-outline" onClick={() => setCount(count + 1)}>
            Increment
          </button>
        </div>
      </div>
    </div>
  );
}

// app/components/client-counter-svelte.svelte
<script lang="ts">
  let { count = 0 } = $props<{ count?: number }>();
</script>

<div class="card bg-base-100 w-96 shadow-sm">
  <div class="card-body">
    <h2 class="card-title">Svelte Counter: {count}</h2>
    <p>A simple Svelte client island with an interactive counter.</p>
    <div class="card-actions">
      <button class="btn btn-outline" onclick={() => count--}>Decrement</button>
      <button class="btn btn-outline" onclick={() => count++}>Increment</button>
    </div>
  </div>
</div>
